version: 2.1

executors:
  ubuntu:
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    machine:
      image: ubuntu-2404:2024.11.1
      docker_layer_caching: true
    resource_class: arm.large

jobs:
  jdk21:
    executor: ubuntu
    steps:
      - run: sudo apt-get update
      - run: sudo apt install openjdk-21-jdk
      - checkout
      - run: ./gradlew build
  jdk23:
    executor: ubuntu
    steps:
      - run: sudo apt-get update
      - run: sudo apt install openjdk-23-jdk
      - checkout
      - run: ./gradlew build

workflows:
  gradle-build:
    jobs:
      - jdk21
      - jdk23
