spring:
  redisson:
    config:
      single-server-config:
        address: redis://livk.com:6379
        password: 123456
        database: 7
        idleConnectionTimeout: 10000
        connectTimeout: 10000
        timeout: 3000
        retryAttempts: 3
        retryInterval: 1500
        subscriptionTimeout: 15000
        subscriptionsPerConnection: 10
        subscriptionConnectionMinimumIdleSize: 1
        subscriptionConnectionPoolSize: 100
        connectionMinimumIdleSize: 32
        connectionPoolSize: 64
        dnsMonitoringInterval: 5000
      threads: 0
      nettyThreads: 0
      codec: "!<org.redisson.codec.JsonJacksonCodec> {}"
      transportMode: "NIO"
