spring:
  dynamic:
    datasource:
      mysql:
        url: jdbc:mysql://livk.com:3306/mybatis?createDatabaseIfNotExist=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
      pgsql:
        url: jdbc:postgresql://livk.com:5432/mybatis
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
    primary: mysql
